# --*-- coding: utf8 --*--
#
import pandas as pd


countries_conf = [
    "China",
    "Canada",
    "Brazil",
    "Russia",
    "United States",
    "Unknown Country",
    "Somalia",
    "Liechtenstein",
    "Morocco",
    "W. Sahara",
    "Serbia",
    "Afghanistan",
    "Angola",
    "Albania",
    "Aland",
    "Andorra",
    "United Arab Emirates",
    "Argentina",
    "Armenia",
    "American Samoa",
    "Fr. S. Antarctic Lands",
    "Antigua and Barb.",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Burundi",
    "Belgium",
    "Benin",
    "Burkina Faso",
    "Bangladesh",
    "Bulgaria",
    "Bahrain",
    "Bahamas",
    "Bosnia and Herz.",
    "Belarus",
    "Belize",
    "Bermuda",
    "Bolivia",
    "Barbados",
    "Brunei",
    "Bhutan",
    "Botswana",
    "Central African Rep.",
    "Switzerland",
    "Chile",
    "Côte d'Ivoire",
    "Cameroon",
    "Dem. Rep. Congo",
    "Congo",
    "Colombia",
    "Comoros",
    "Cape Verde",
    "Costa Rica",
    "Cuba",
    "Curaçao",
    "Cayman Is.",
    "N. Cyprus",
    "Cyprus",
    "Czech Rep.",
    "Germany",
    "Djibouti",
    "Dominica",
    "Denmark",
    "Dominican Rep.",
    "Algeria",
    "Ecuador",
    "Egypt",
    "Eritrea",
    "Spain",
    "Estonia",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Is.",
    "France",
    "Faeroe Is.",
    "Micronesia",
    "Gabon",
    "United Kingdom",
    "Georgia",
    "Ghana",
    "Guinea",
    "Gambia",
    "Guinea-Bissau",
    "Eq. Guinea",
    "Greece",
    "Grenada",
    "Greenland",
    "Guatemala",
    "Guam",
    "Guyana",
    "Heard I. and McDonald Is.",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Isle of Man",
    "India",
    "Br. Indian Ocean Ter.",
    "Ireland",
    "Iran",
    "Iraq",
    "Iceland",
    "Israel",
    "Italy",
    "Jamaica",
    "Jersey",
    "Jordan",
    "Japan",
    "Siachen Glacier",
    "Kazakhstan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "Korea",
    "Kuwait",
    "Lao PDR",
    "Lebanon",
    "Liberia",
    "Libya",
    "Saint Lucia",
    "Sri Lanka",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Moldova",
    "Madagascar",
    "Mexico",
    "Macedonia",
    "Mali",
    "Malta",
    "Myanmar",
    "Montenegro",
    "Mongolia",
    "N. Mariana Is.",
    "Mozambique",
    "Mauritania",
    "Montserrat",
    "Mauritius",
    "Malawi",
    "Malaysia",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Nigeria",
    "Nicaragua",
    "Niue",
    "Netherlands",
    "Norway",
    "Nepal",
    "New Zealand",
    "Oman",
    "Pakistan",
    "Panama",
    "Peru",
    "Philippines",
    "Palau",
    "Papua New Guinea",
    "Poland",
    "Puerto Rico",
    "Dem. Rep. Korea",
    "Portugal",
    "Paraguay",
    "Palestine",
    "Fr. Polynesia",
    "Qatar",
    "Romania",
    "Rwanda",
    "Saudi Arabia",
    "Sudan",
    "S. Sudan",
    "Senegal",
    "Singapore",
    "S. Geo. and S. Sandw. Is.",
    "Saint Helena",
    "Solomon Is.",
    "Sierra Leone",
    "El Salvador",
    "St. Pierre and Miquelon",
    "São Tomé and Principe",
    "Suriname",
    "Slovakia",
    "Slovenia",
    "Sweden",
    "Swaziland",
    "Seychelles",
    "Syria",
    "Turks and Caicos Is.",
    "Chad",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Turkmenistan",
    "Timor-Leste",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Tanzania",
    "Uganda",
    "Ukraine",
    "Uruguay",
    "Uzbekistan",
    "St. Vin. and Gren.",
    "Venezuela",
    "U.S. Virgin Is.",
    "Vietnam",
    "Vanuatu",
    "Samoa",
    "Yemen",
    "South Africa",
    "Zambia",
    "Zimbabwe",
]

location_dict = {
    "Solomon Islands": "Solomon Is.",
    "North Korea": "Korea",
    "Taiwan (Province of China)": "Taiwan",
    "Bosnia and Herzegovina": "Bosnia and Herz.",
    "Laos": "Lao PDR",
    # "Maldives": "",
    "South Sudan": "S. Sudan",
    "South Korea": "Dem. Rep. Korea",
    "Virgin Islands, U.S.": "U.S. Virgin Is.",
    "Antigua and Barbuda": "Antigua and Barb.",
    "The Gambia": "Gambia",
    # "Saint Vincent and the Grenadines": "",
    # "Marshall Islands": "",
    "Cote d'Ivoire": "Côte d'Ivoire",
    "The Bahamas": "Bahamas",
    "Sao Tome and Principe": "São Tomé and Principe",
    "Central African Republic": "Central African Rep.",
    "Russian Federation": "Russia",
    "Democratic Republic of the Congo": "Dem. Rep. Congo",
    "Northern Mariana Islands": "N. Mariana Is.",
    "Dominican Republic": "Dominican Rep.",
    "Czech Republic": "Czech Rep.",
    "Equatorial Guinea": "Eq. Guinea",
    "Federated States of Micronesia": "Micronesia",
}

countries_dict = {
    "Antigua and Barbuda": "Antigua and Barb.",
    "Bahamas, The": "Bahamas",
    "Bosnia and Herzegovina": "Bosnia and Herz.",
    "Brunei Darussalam": "Brunei",
    "Central African Republic": "Central African Rep.",
    "Cote d'Ivoire": "Côte d'Ivoire",
    "Congo, Dem. Rep.": "Dem. Rep. Congo",
    "Congo, Rep.": "Congo",
    "Cabo Verde": "Cape Verde",
    "Cayman Islands": "Cayman Is.",
    "Czech Republic": "Czech Rep.",
    "Dominican Republic": "Dominican Rep.",
    "Egypt, Arab Rep.": "Egypt",
    "Micronesia, Fed. Sts.": "Micronesia",
    "Gambia, The": "Gambia",
    "Equatorial Guinea": "Eq. Guinea",
    "Iran, Islamic Rep.": "Iran",
    "Kyrgyz Republic": "Kyrgyzstan",
    "Korea, Rep.": "Korea",
    "St. Lucia": "Saint Lucia",
    "North Macedonia": "Macedonia",
    "Northern Mariana Islands": "",
    "Korea, Dem. People’s Rep.": "Dem. Rep. Korea",
    "French Polynesia": "Fr. Polynesia",
    "Russian Federation": "Russia",
    "Solomon Islands": "Solomon Is.",
    "South Sudan": "S. Sudan",
    "Sao Tome and Principe": "São Tomé and Principe",
    "Slovak Republic": "Slovakia",
    "Syrian Arab Republic": "Syria",
    "Turks and Caicos Islands": "Turks and Caicos Is.",
    "Venezuela, RB": "Venezuela",
    "Virgin Islands (U.S.)": "U.S. Virgin Is.",
    "Yemen, Rep.": "Yemen",
}


# df = pd.read_csv("HIV_global.csv")
# print(df.location.unique())
# for _loc in df.location.unique().tolist():
#     if _loc not in countries_conf:
#         print(_loc)


# df = pd.read_csv("GDP_global.csv", encoding="gbk")
# # print(df["Country Name"].unique())
# for _loc in df["Country Name"].unique().tolist():
#     if _loc not in countries_conf:
#         print(_loc)







